create table if not exists public.safari_enquiries (
  id bigint generated by default as identity primary key,
  enquiry_id text not null unique,
  specialist text not null,
  source text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.safari_enquiries enable row level security;

comment on table public.safari_enquiries is
  'Private Safari Crafters briefs. Access is server-side through the service role only.';
